services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=web
      - traefik.http.routers.frontend-http.rule=HostRegexp(`^.+$`)

  proxy:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
    userns_mode: host

  tunnel:
    image: cloudflare/cloudflared:2026.7.3
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN?No TUNNEL_TOKEN set}
    command:
      - tunnel
      - --no-autoupdate
      - run
